### ISSUE TITLE
Don't show mark in selectDays

### ISSUE THREAD

**Issue by YUTTHANAI** [braintonik/dialogPlugIn#1]
local op = { top = 100, left = 10, wDialog = display.contentWidth-20, hDialog = 400, 
                 overideBkInput = true, overideBkColor = {0,0,0,0.8},
                 templateStyle = "classic", dateNumberFontSize = 20, 
                 dateSelectedAsCircle = true, weekEndNumberColor = {1,0,0},
                 selectDays = "2017-5-18,2017-4-19,2017-4-20,2017-4-21", dateBkUnderlineSelected = {1,0,0,1},
                 buttonHandler = dateListener }
    local datePicker = braintonikDialog.displayCalendarDialog( op )
    
------------------------------
In this source code it's not show underline on select date.

**Comment by braintonik** [comment]
This is now working in the latest version.
