### ISSUE TITLE
Error in Carousel dialog when trying to swipe between items

### ISSUE THREAD

**Issue by cmorgan76** [braintonik/dialogPlugIn#3]
08-26 04:24:45.100 14736 16808 I Corona  : ERROR: Runtime error
08-26 04:24:45.100 14736 16808 I Corona  : ?:0: attempt to call global 'mAbs' (a nil value)
08-26 04:24:45.100 14736 16808 I Corona  : stack traceback:
08-26 04:24:45.100 14736 16808 I Corona  :      ?: in function 'method'
08-26 04:24:45.100 14736 16808 I Corona  :      /Users/jenkins/slaveroot/workspace/Templates/label/android/platform/resources/init.lua:221: in function </Users/jenkins/slaveroot/workspace/Templates/label/android/platform/resources/init.lua:190>

-------------------------------------------------

Samsung Galaxy S6 (Android Version 7)

Corona Version: 3.0.0
Build: 2017.3119
Platform: GT-I9300 / x64 / 10.0 / Intel(R) HD Graphics 4600 / 4.3.0 - Build 20.19.15.4624 / 2017.3119 / en_US | US | en_US | en

**Comment by braintonik** [comment]
This is now fixed in the latest version
